### ISSUE TITLE
Investigate whether we can use UTF-8 file encoding

### ISSUE THREAD

**Issue by IntermittentlyRupert** [IntermittentlyRupert/hpnofp-ebook#11]
See if it's possible to move away from using hex codes for non-ASCII characters.

**Comment by ThrawnCA** [comment]
What's wrong with numeric codes? They're very portable, they copy-paste well, they show up well in file diffs.

**Comment by IntermittentlyRupert** [comment]
They're less human-readable and it's easy to miss a non-ASCII character when adding a new chapter (I actually raised this because you picked up a couple I'd missed in your latest PR). I'd rather just support UTF-8 and not have to worry about it.

This also goes pretty hand-in-hand with #10. Curly quotes make for a much nicer reading experience, but every single quote and apostrophe being 7 characters long (and looking up which code is which when working with the files) is going to get annoying.
