### ISSUE TITLE
Include authorised one-shots?

### ISSUE THREAD

**Issue by ThrawnCA** [IntermittentlyRupert/hpnofp-ebook#17]
There are some authorised one-shot recursive fanfics of NoFP; I know of https://www.fanfiction.net/s/10213764/1/G-for-Ginevra and https://www.fanfiction.net/s/4019762/1/A-Night-at-the-Burrow-A-Fan-Short

Should those be included, perhaps among the regular chapters, perhaps as appendices?

**Comment by IntermittentlyRupert** [comment]
I haven't seen these before and I haven't read them.

I have a weak preference for not including them, since they're not strictly part of the story. That said, I don't have any strong objections to you adding them as appendices if you really want them in there.

**Comment by ThrawnCA** [comment]
Ah. They're the only two I've found, but I recommend checking them out. Especially "A Night at the Burrow".

I'll see if I can do an appendix.

**Comment by ThrawnCA** [comment]
Ok, I have a branch, but I'm on mobile, so I can't do the smart quote replacement. Also need to fix non-ASCII characters to be UTF-8.

**Comment by ThrawnCA** [comment]
Pull request #18 is ready.
