### ISSUE TITLE
Sync with Royal Road chapters

### ISSUE THREAD

**Issue by ThrawnCA** [IntermittentlyRupert/hpnofp-ebook#31]
Royal Road has been updated (hooray!) to chapter 29. We should trawl the new chapters to see if the Authorlord has changed anything worth incorporating into the eBook.

I've already adjusted a few minor bits of punctuation in chapter 2, will push soon.

**Comment by ThrawnCA** [comment]
Ooh, it's all the way up to chapter 43 now.

**Comment by ThrawnCA** [comment]
Heh, releasing 2.2.5 might have been a bit hasty. I still have 41 more chapters to go through!

**Comment by IntermittentlyRupert** [comment]
I've got the release action configured to run on merge. If someone's enthusiastic enough to download the new version immediately, they're welcome to it. 😄

**Comment by ThrawnCA** [comment]
Should I be targeting an intermediate branch, then?

Personally, I would prefer to keep releases manual. But it's your repo.

**Comment by IntermittentlyRupert** [comment]
I'm not super fussed either way. If you'd rather it all go out at once, I'm happy to accept all the chapters in one PR.

**Comment by IntermittentlyRupert** [comment]
@ThrawnCA It looks like this is complete with #34? If there's anything left that you're planning to do let me know and I'll reopen this.

**Comment by ThrawnCA** [comment]
I've finished the sweep to compare it with Royal Road, yes :)
