### ISSUE TITLE
Author notes

### ISSUE THREAD

**Issue by ThrawnCA** [IntermittentlyRupert/hpnofp-ebook#33]
I'm most of the way through comparing the Royal Road chapters with the current eBook chapters - pull request coming soon! - and I'm wondering what, if anything, we should do with the author notes. They appear to have been copied in full from the lost FFN chapters, so we do have the opportunity to preserve commentary such as the explanation of what happened to Severus Snape in the first timeline (chapter 34) and the increased maturity of Harry's friends (chapter 29).

Should we incorporate them into the chapters? Or perhaps add an appendix listing all the notes?

**Comment by IntermittentlyRupert** [comment]
Awesome, appreciate it.

Yeah, it might be nice to include the author notes for posterity. I have a moderate preference for keeping them out of the normal reading flow, so my ideal would be an appendix with nav links to/from each chapter to easily get back and forth.

**Comment by ThrawnCA** [comment]
Pull request should be ready now :)

**Comment by IntermittentlyRupert** [comment]
Thanks - I'll try to have a look later this weekend (but also I just moved house so apologies if it takes a little while). 🙃

**Comment by ThrawnCA** [comment]
> but also I just moved house

Congrats, so did we! From a regular yard, probably about 450m², out to acreage (nearly 10000). House is kind of old and needs work, but it has potential.

Settling in okay?

**Comment by IntermittentlyRupert** [comment]
_**Narrator:** He did not have a look later that weekend._

You must have a much higher tolerance for yard work than I do... 😅 But that sounds great! Similar situation here with the place needing a fair bit of work, but it'll be great once I get through all of that. I'm getting to the tail end of the "shuffling boxes and furniture around to make space as I unpack" and I'll be very happy once that's complete.

Your PRs are both merged. I've paused the automated release to hopefully look at adding those back/forth links today.

**Comment by IntermittentlyRupert** [comment]
That should be done now, at least for a first pass. I'm not wedded to any of the details, so if you had different/better ideas for how it should be done, happy to take a PR for it. Otherwise I'll close this issue and do a release.

**Comment by ThrawnCA** [comment]
The one thing I was disappointed about is that I couldn't find a way to link from the chapter directly to the specific author note. I had to settle for linking to the author notes page as a whole. Either ePUB format doesn't allow directly linking to anchors within a page, or I just didn't get the syntax right. Edit: Oh, right, you already amended it.

**Comment by IntermittentlyRupert** [comment]
Yeah, the version I've pushed works for me in Calibre's reader (epub) and on Kindle (mobi). Not sure about any readers, though, and it also occurs to me that I didn't test how it works in the PDF version... I should probably check that.
