### ISSUE TITLE
Script the conversion from EPUB to PDF

### ISSUE THREAD

**Issue by IntermittentlyRupert** [IntermittentlyRupert/hpnofp-ebook#6]

**Comment by ThrawnCA** [comment]
Looks like [mutool](https://mupdf.com/docs/manual-mutool-convert.html) can do this pretty easily. I'll add a conditional block to the build script, shall I?

**Comment by ThrawnCA** [comment]
Need to check whether ebook-convert can do this if present (it probably can).

**Comment by IntermittentlyRupert** [comment]
Here's my notes for changes I make to Calibre's default EPUB->PDF conversion settings for the current manual PDF generation process:

```
Page Setup
============
Output:             Default Output Profile
Input:              Default Input Profile

PDF Output
============
Paper Size:         A4
Page numbers:       Yes
Serif family:       Adobe Garamond Pro
Standard font:      serif
Default font size:  30px
Page margins:       72pt
```

**Comment by ThrawnCA** [comment]
I don't seem to have access to Adobe Garamond Pro, and specifying a default font size of 30 gives very bloated text. However, specifying the page size is very helpful (the default is 'letter' which doesn't work well).

**Comment by IntermittentlyRupert** [comment]
Yeah, I've got Adobe Garamond by way of Photoshop.

You should be fine to substitute EB Garamond, which is freely available on [Google Fonts](https://fonts.google.com/specimen/EB+Garamond) (WOFF2) and [github](https://github.com/google/fonts/tree/master/ofl/ebgaramond) (TTF) under the Open Font License. It's Close Enough if Adobe Garamond isn't available ([here's a comparison](http://www.identifont.com/differences?first=EB+Garamond&second=Adobe+Garamond)).

I'd prefer for the script to check for the existence of Adobe Garamond first, though, because it's a smidge nicer in a bunch of small ways. It can then fall back to EB Garamond or the system default as needed.

Default font size will have to vary by typeface.
